[env]
platform = espressif32@6.4.0
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
; Enable the OPI PSRAM required for the XIAO ESP32 S3 Sense
board_build.arduino.memory_type = qio_opi
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue


; Run the models from Edge Impulse
[env:keyword_spotting_inference]
build_src_filter = +<*> -<object_detection_inference.cpp> -<record_audio.cpp> -<record_image.cpp> -<save_data.cpp>
lib_deps = 
    lib/keyword_spotting_xiaoesp32s3_inferencing 
lib_ignore = 
    object_detection_xiaoesp32s3_inferencing

[env:object_detection_inference]
build_src_filter = +<*> -<keyword_spotting_inference.cpp> -<record_audio.cpp> -<record_image.cpp> -<save_data.cpp>
lib_deps = 
    lib/object_detection_xiaoesp32s3_inferencing
    https://github.com/eloquentarduino/EloquentEsp32cam.git
lib_ignore = 
    keyword_spotting_xiaoesp32s3_inferencing
build_flags = 
    ${env.build_flags}
    -DCORE_DEBUG_LEVEL=5

; Record audio
[env:record_audio]

build_src_filter = +<*> -<keyword_spotting_inference.cpp> -<object_detection_inference.cpp> -<record_image.cpp> -<save_data.cpp>

; Record image
[env:record_image]
build_src_filter = +<*> -<keyword_spotting_inference.cpp> -<object_detection_inference.cpp> -<record_audio.cpp> -<save_data.cpp>

; Configure the board for storage mode, which allows the board to be used as a USB mass storage device to copy files to and from the PSRAM
[env:save_data]
build_src_filter = +<*> -<keyword_spotting_inference.cpp> -<object_detection_inference.cpp> -<record_audio.cpp> -<record_image.cpp>
